#!/usr/bin/python
# 
import os
from datetime import datetime

olddate = 0

os.system('sleep 10')

def set_wallpaper_1():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur1.png");
    }'
    """)

def set_wallpaper_2():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur2.png");
    }'
    """)

def set_wallpaper_3():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur3.png");
    }'
    """)

def set_wallpaper_4():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur4.png");
    }'
    """)

def set_wallpaper_5():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur5.png");
    }'
    """)

def set_wallpaper_6():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur6.png");
    }'
    """)

def set_wallpaper_7():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur7.png");
    }'
    """)

def set_wallpaper_8():
    os.system("""    
    dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
    var Desktops = desktops();                                                                                                                       
    for (i=0;i<Desktops.length;i++) {
            d = Desktops[i];
            d.wallpaperPlugin = "org.kde.image";
            d.currentConfigGroup = Array("Wallpaper",
                                        "org.kde.image",
                                        "General");
            d.writeConfig("Image", "file:///usr/share/bigsur_dynamic/bigsur8.png");
    }'
    """)


while (True):
    date = datetime.now()
    date = date.hour
    if (date == olddate):
        print('Nothing to do')
    else:
        if (date >= 20):
            set_wallpaper_2()
            print('Bigsur 2 set')
        elif (date >= 18):
            set_wallpaper_8() 
            print('Bigsur 8 set')
        elif (date >= 17):
            set_wallpaper_7() 
            print('Bigsur 7 set')  
        elif (date >= 15):
            set_wallpaper_6() 
            print('Bigsur 6 set')
        elif (date >= 12):
            set_wallpaper_1() 
            print('Bigsur 1 set')
        elif (date >= 9):
            set_wallpaper_5() 
            print('Bigsur 5 set')
        elif (date >= 7):
            set_wallpaper_4() 
            print('Bigsur 4 set')
        elif (date >= 5):
            set_wallpaper_3() 
            print('Bigsur 3 set')
        else:
            set_wallpaper_2()
            print('Bigsur 2 set')
    olddate = date
    os.system('sleep 10')
